"""phase2_ticket_core

Revision ID: 2eac52c63f9d
Revises: 0fc4b90f44cf
Create Date: 2026-06-14 21:44:32.692070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2eac52c63f9d'
down_revision = '0fc4b90f44cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role_label', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('Backlog', 'InProgress', 'Done', 'Cancelled', name='status'), nullable=False),
    sa.Column('priority', sa.Enum('Low', 'Medium', 'High', 'Urgent', name='priority'), nullable=False),
    sa.Column('product', sa.Enum('GovEntry', 'GovSupply', 'GovRewards', name='product'), nullable=True),
    sa.Column('issue_type', sa.Enum('FeatureRequest', 'Bug', 'UserGuideQuestion', 'RegistrationEvent', name='issuetype'), nullable=True),
    sa.Column('source', sa.Enum('web', 'intake', 'formsg', 'goventry', name='source'), nullable=False),
    sa.Column('source_ref', sa.String(length=255), nullable=True),
    sa.Column('requester_name', sa.String(length=255), nullable=True),
    sa.Column('requester_email', sa.String(length=255), nullable=True),
    sa.Column('agency_id', sa.Integer(), nullable=False),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.Column('ai_triage_json', sa.JSON(), nullable=True),
    sa.Column('ai_draft_reply', sa.Text(), nullable=True),
    sa.Column('triaged_at', sa.DateTime(), nullable=True),
    sa.Column('resolution_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.ForeignKeyConstraint(['assignee_id'], ['team_members.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_ref')
    )
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_issues_agency_id'), ['agency_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('issue_id', sa.Integer(), nullable=True),
    sa.Column('agency_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('issue_agencies',
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('agency_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('issue_id', 'agency_id')
    )
    op.create_table('knowledge_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_type', sa.Enum('doc', 'resolved_ticket', name='sourcetype'), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=True),
    sa.Column('agency_id', sa.Integer(), nullable=True),
    sa.Column('visibility', sa.Enum('agency_specific', 'global_sanitized', 'internal_admin_only', name='visibility'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticket_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.Enum('outbound', 'inbound', 'note', name='direction'), nullable=False),
    sa.Column('sender_name', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ticket_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticket_messages_issue_id'), ['issue_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_messages_issue_id'))

    op.drop_table('ticket_messages')
    op.drop_table('knowledge_entries')
    op.drop_table('issue_agencies')
    op.drop_table('audit_logs')
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_issues_agency_id'))

    op.drop_table('issues')
    op.drop_table('team_members')
    # ### end Alembic commands ###
