"""phase3_approval_queue

Revision ID: 6023c1062122
Revises: 2eac52c63f9d
Create Date: 2026-06-14 22:53:28.403296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6023c1062122'
down_revision = '2eac52c63f9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proposed_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.Enum('reply', 'status_change', 'assignment', 'tag_change', 'internal_note', name='actiontype'), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('proposer', sa.String(length=100), nullable=False),
    sa.Column('proposed_payload', sa.JSON(), nullable=False),
    sa.Column('final_payload', sa.JSON(), nullable=True),
    sa.Column('required_tier', sa.Enum('auto', 'human', 'admin', name='approvaltier'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'executed', 'failed', name='proposalstatus'), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('proposed_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proposed_actions_issue_id'), ['issue_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proposed_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proposed_actions_issue_id'))

    op.drop_table('proposed_actions')
    # ### end Alembic commands ###
